### ISSUE TITLE
while loop in python script causing high CPU consumption?

### ISSUE THREAD

**Issue by MatthewJohn** [katzcreates/BMOctoprint#1]
I've just seen your video and looked at your python script..
I'm not sure if I'm missing something (in particular about how gpiozero.Button works)..
Looking at the documentation and how you're using gpiozero.Button, I think either of one these is true, which may cause unnecessary CPU usage:
 * Looping and checking each of the buttons - I imagine this is causing a high amount of CPU load? If octoprint is running in the background, maybe this could cause some print issues - perhaps a very small sleep at end of the for while loop would work (https://github.com/katzcreates/BMOctoprint/blob/main/Code%20Files/BMOFaceButtons.py#L68)?
```
    from time import sleep
    while True:
        button_right.when_pressed = video_right
        button_up.when_pressed = video_up
        button_down.when_pressed = video_down
        button_left.when_pressed = video_left
        sleep(0.1)

    pause()
```
 * Alternatively (and if true, a more beneficial change), having had a brief look at the docs/example for gpiozero.Button:
```
    from gpiozero import LED, Button:
    from signal import pause
    
    led = LED(17)
    button = Button(3)
    
    button.when_pressed = led.on
    button.when_released = led.off
    
    pause()
```
   the example appears to suggest that button.when_pressed is just setting up a callback for when the button is pressed. Therefore, once entering the thread `pause()`, the callback will happen, meaning the `while` loop is not necessary at all re-setting up the callback over and over, wasting CPU time. So it could look like:
```
    button_right.when_pressed = video_right
    button_up.when_pressed = video_up
    button_down.when_pressed = video_down
    button_left.when_pressed = video_left

    pause()
```

Apologies if I've missed something (either obvious or not) and I have absolutely no means of testing any of this (PI, 3d printer or BMO) :D

**Comment by katzcreates** [comment]
> I've just seen your video and looked at your python script.. I'm not sure if I'm missing something (in particular about how gpiozero.Button works).. Looking at the documentation and how you're using gpiozero.Button, I think either of one these is true, which may cause unnecessary CPU usage:
> 
> * Looping and checking each of the buttons - I imagine this is causing a high amount of CPU load? If octoprint is running in the background, maybe this could cause some print issues - perhaps a very small sleep at end of the for while loop would work (https://github.com/katzcreates/BMOctoprint/blob/main/Code%20Files/BMOFaceButtons.py#L68)?
> 
> ```
>     from time import sleep
>     while True:
>         button_right.when_pressed = video_right
>         button_up.when_pressed = video_up
>         button_down.when_pressed = video_down
>         button_left.when_pressed = video_left
>         sleep(0.1)
> 
>     pause()
> ```
> 
> * Alternatively (and if true, a more beneficial change), having had a brief look at the docs/example for gpiozero.Button:
> 
> ```
>     from gpiozero import LED, Button:
>     from signal import pause
>     
>     led = LED(17)
>     button = Button(3)
>     
>     button.when_pressed = led.on
>     button.when_released = led.off
>     
>     pause()
> ```
> 
> the example appears to suggest that button.when_pressed is just setting up a callback for when the button is pressed. Therefore, once entering the thread `pause()`, the callback will happen, meaning the `while` loop is not necessary at all re-setting up the callback over and over, wasting CPU time. So it could look like:
> 
> ```
>     button_right.when_pressed = video_right
>     button_up.when_pressed = video_up
>     button_down.when_pressed = video_down
>     button_left.when_pressed = video_left
> 
>     pause()
> ```
> 
> Apologies if I've missed something (either obvious or not) and I have absolutely no means of testing any of this (PI, 3d printer or BMO) :D

Hey! Thank you so much for noting this. You are absolutely right; the `while` loop is not necessary and I had just missed that in the documentation. I've tested your theory and it is working perfectly! I shall update the code here so everyone can benefit from your insight. 😀 Thank you so much!

**Comment by MatthewJohn** [comment]
For reference: aa8eac3b318e5cdad17138410bee72f418423924
